import streamlit as st
import pandas as pd
import os
from datetime import datetime
from fpdf import FPDF
from utils.alerts import render_sidebar_alerts

st.set_page_config(page_title="Strategic Audit Report", page_icon="📄", layout="wide")

render_sidebar_alerts()

# PREMIUM THEME
st.markdown("""
<style>
.main { background: #0E1117; color: white; }
.report-card {
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    padding: 30px;
    border-radius: 12px;
}
</style>
""", unsafe_allow_html=True)

st.title("📄 Strategic Infrastructure Audit")

# Load Data
if os.path.exists("gps_log.csv"):
    df = pd.read_csv("gps_log.csv")
else:
    st.warning("Database unavailable.")
    st.stop()

# --- CALCULATE STATISTICS ---
total = len(df)
active = df[df['status'] != 'Resolved'].copy()
resolved = len(df[df['status'] == 'Resolved'])
pending = len(active)

h = len(active[active['severity'] == 'high'])
m = len(active[active['severity'] == 'medium'])
l = len(active[active['severity'] == 'low'])

rhi = 100 - ( (h*20) + (m*8) + (l*2) ) / (total if total > 0 else 1) * 2
rhi = max(0, min(100, rhi))
grade = "A" if rhi > 85 else "B" if rhi > 70 else "C" if rhi > 55 else "D" if rhi > 40 else "F"

# --- PDF GENERATOR CLASS ---
class SRIMS_PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'SRIMS | OFFICIAL INFRASTRUCTURE AUDIT', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 10, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_pdf():
    pdf = SRIMS_PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Executive Summary Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="1. EXECUTIVE SUMMARY", ln=True, align='L')
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Current Integrity Index (RHI): {rhi:.1f}%", ln=True)
    pdf.cell(200, 10, txt=f"Strategic Health Grade: {grade}", ln=True)
    pdf.cell(200, 10, txt=f"Total Inspected Data Points: {total}", ln=True)
    pdf.cell(200, 10, txt=f"Successfully Rectified Assets: {resolved}", ln=True)
    pdf.ln(5)

    # Operational Risks
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="2. ACTIVE OPERATIONAL RISKS", ln=True, align='L')
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"- Critical (High Severity): {h}", ln=True)
    pdf.cell(200, 10, txt=f"- Serious (Medium Severity): {m}", ln=True)
    pdf.cell(200, 10, txt=f"- Minor (Low Severity): {l}", ln=True)
    pdf.ln(5)

    # Procurement & Costs
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="3. PROCUREMENT & FISCAL FORECAST", ln=True, align='L')
    pdf.set_font("Arial", size=12)
    mat_tons = (h*1.2) + (m*0.5) + (l*0.2)
    est_cost = pending * 3500
    pdf.cell(200, 10, txt=f"- Estimated Asphalt Mix Required: {mat_tons:.1f} Tons", ln=True)
    pdf.cell(200, 10, txt=f"- Estimated Financial Liability: INR {est_cost:,}", ln=True)
    pdf.cell(200, 10, txt=f"- Projected Labor Requirement: {pending * 4} Man-hours", ln=True)
    pdf.ln(5)

    # Strategic Priority Table
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="4. TOP STRATEGIC PRIORITIES (ROI)", ln=True, align='L')
    pdf.set_font("Arial", 'B', 10)
    
    # Table Header
    pdf.cell(30, 10, 'Task ID', 1)
    pdf.cell(50, 10, 'Damage Type', 1)
    pdf.cell(50, 10, 'Location', 1)
    pdf.cell(30, 10, 'Severity', 1)
    pdf.cell(30, 10, 'ROI Score', 1)
    pdf.ln()

    # Table Data
    pdf.set_font("Arial", size=9)
    if not active.empty:
        cost_map = {'high': 8500, 'medium': 3500, 'low': 1500}
        active['roi'] = (active['confidence'] * 100) / active['severity'].map(cost_map)
        top_5 = active.sort_values(by='roi', ascending=False).head(8)
        
        for i, row in top_5.iterrows():
            pdf.cell(30, 10, str(row['task_id']), 1)
            pdf.cell(50, 10, str(row['damage_type']), 1)
            pdf.cell(50, 10, str(row['location_label']), 1)
            pdf.cell(30, 10, str(row['severity']).upper(), 1)
            pdf.cell(30, 10, f"{row['roi']:.2f}", 1)
            pdf.ln()
    else:
        pdf.cell(190, 10, 'No active maintenance requirements.', 1, ln=True, align='C')

    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Internal Strategic Audit - Generated by SRIMS Autonomous Intelligence", 0, 1, 'C')

    return bytes(pdf.output())

# --- UI ---
st.markdown("<div class='report-card'>", unsafe_allow_html=True)
st.header("📋 Official Strategic Audit (PDF)")
st.write("Generate a formal infrastructure report for municipal submission.")

pdf_bytes = create_pdf()

st.download_button(
    label="📩 Generate & Download Strategic PDF Audit",
    data=pdf_bytes,
    file_name=f"SRIMS_Audit_{datetime.now().strftime('%Y%m%d')}.pdf",
    mime="application/pdf",
    use_container_width=True
)
st.markdown("</div>", unsafe_allow_html=True)

st.divider()
st.subheader("📊 Master Operational Log")
st.dataframe(df, use_container_width=True, hide_index=True)