import streamlit as st
import pandas as pd
import os
from datetime import datetime
from fpdf import FPDF
from utils.alerts import render_sidebar_alerts
from utils.style import apply_custom_style, render_modern_card, render_top_nav

st.set_page_config(page_title="Strategic Audit | SRIMS", page_icon="📄", layout="wide")

# Apply global styling
apply_custom_style()

# Top Navbar
render_top_nav("Report")

render_sidebar_alerts()

# Page Header
st.markdown("""
<div class="animate-in" style="margin-bottom: 30px;">
    <h1><i class="fa-solid fa-file-invoice" style="color: var(--primary-blue);"></i> Strategic Infrastructure Audit</h1>
    <p style="color: var(--text-slate-600);">Formatted reporting and official documentation for municipal planning and procurement.</p>
</div>
""", unsafe_allow_html=True)

# Load Data
if os.path.exists("gps_log.csv"):
    df = pd.read_csv("gps_log.csv")
else:
    st.warning("Spatial database unavailable. Please run a detection mission first.")
    st.stop()

# --- CALCULATE STATISTICS ---
total = len(df)
active = df[df['status'] != 'Resolved'].copy()
resolved = len(df[df['status'] == 'Resolved'])
pending = len(active)

h = len(active[active['severity'] == 'high'])
m = len(active[active['severity'] == 'medium'])
l = len(active[active['severity'] == 'low'])

rhi = 100 - ( (h*20) + (m*8) + (l*2) ) / (total if total > 0 else 1) * 2
rhi = max(0, min(100, rhi))
grade = "A" if rhi > 85 else "B" if rhi > 70 else "C" if rhi > 55 else "D" if rhi > 40 else "F"

# --- PDF GENERATOR CLASS ---
class SRIMS_PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'SRIMS | OFFICIAL INFRASTRUCTURE AUDIT', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 10, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_pdf():
    pdf = SRIMS_PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Executive Summary Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="1. EXECUTIVE SUMMARY", ln=True, align='L')
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Current Integrity Index (RHI): {rhi:.1f}%", ln=True)
    pdf.cell(200, 10, txt=f"Strategic Health Grade: {grade}", ln=True)
    pdf.cell(200, 10, txt=f"Total Inspected Data Points: {total}", ln=True)
    pdf.cell(200, 10, txt=f"Successfully Rectified Assets: {resolved}", ln=True)
    pdf.ln(5)

    # Operational Risks
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="2. ACTIVE OPERATIONAL RISKS", ln=True, align='L')
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"- Critical (High Severity): {h}", ln=True)
    pdf.cell(200, 10, txt=f"- Serious (Medium Severity): {m}", ln=True)
    pdf.cell(200, 10, txt=f"- Minor (Low Severity): {l}", ln=True)
    pdf.ln(5)

    # Procurement & Costs
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="3. PROCUREMENT & FISCAL FORECAST", ln=True, align='L')
    pdf.set_font("Arial", size=12)
    mat_tons = (h*1.2) + (m*0.5) + (l*0.2)
    est_cost = pending * 3500
    pdf.cell(200, 10, txt=f"- Estimated Asphalt Mix Required: {mat_tons:.1f} Tons", ln=True)
    pdf.cell(200, 10, txt=f"- Estimated Financial Liability: INR {est_cost:,}", ln=True)
    pdf.cell(200, 10, txt=f"- Projected Labor Requirement: {pending * 4} Man-hours", ln=True)
    pdf.ln(5)

    # Strategic Priority Table
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="4. TOP STRATEGIC PRIORITIES (ROI)", ln=True, align='L')
    pdf.set_font("Arial", 'B', 10)
    
    # Table Header
    pdf.cell(30, 10, 'Task ID', 1)
    pdf.cell(50, 10, 'Damage Type', 1)
    pdf.cell(50, 10, 'Location', 1)
    pdf.cell(30, 10, 'Severity', 1)
    pdf.cell(30, 10, 'ROI Score', 1)
    pdf.ln()

    # Table Data
    pdf.set_font("Arial", size=9)
    if not active.empty:
        cost_map = {'high': 8500, 'medium': 3500, 'low': 1500}
        active['roi'] = (active['confidence'] * 100) / active['severity'].map(cost_map)
        top_5 = active.sort_values(by='roi', ascending=False).head(8)
        
        for i, row in top_5.iterrows():
            pdf.cell(30, 10, str(row['task_id']), 1)
            pdf.cell(50, 10, str(row['damage_type']), 1)
            pdf.cell(50, 10, str(row['location_label']), 1)
            pdf.cell(30, 10, str(row['severity']).upper(), 1)
            pdf.cell(30, 10, f"{row['roi']:.2f}", 1)
            pdf.ln()
    else:
        pdf.cell(190, 10, 'No active maintenance requirements.', 1, ln=True, align='C')

    pdf.ln(10)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Internal Strategic Audit - Generated by SRIMS Autonomous Intelligence", 0, 1, 'C')

    return bytes(pdf.output())

# --- UI ---
st.markdown("### <i class='fa-solid fa-file-pdf' style='color: var(--primary-blue);'></i> Document Generation", unsafe_allow_html=True)
st.markdown("""
<div class="modern-card animate-in" style="background: #F8FAFC;">
    <p style="color: var(--text-slate-600); font-size: 1.1rem; margin-bottom: 20px;">
        Compile official municipal infrastructure reports including structural grades, 
        fiscal liabilities, and priority work schedules.
    </p>
</div>
""", unsafe_allow_html=True)

pdf_bytes = create_pdf()

st.markdown('<div class="action-btn">', unsafe_allow_html=True)
st.download_button(
    label="📩 GENERATE & DOWNLOAD PDF AUDIT",
    data=pdf_bytes,
    file_name=f"SRIMS_Audit_{datetime.now().strftime('%Y%m%d')}.pdf",
    mime="application/pdf",
    use_container_width=True
)
st.markdown('</div>', unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)
st.divider()

st.markdown("### <i class='fa-solid fa-database' style='color: var(--primary-blue);'></i> Master Operational Log", unsafe_allow_html=True)
st.dataframe(
    df, 
    use_container_width=True, 
    hide_index=True,
    column_config={
        "confidence": st.column_config.ProgressColumn("Accuracy", min_value=0, max_value=1),
        "lat": st.column_config.NumberColumn("Latitude", format="%.4f"),
        "lon": st.column_config.NumberColumn("Longitude", format="%.4f")
    }
)